services:

  postgresdb:
    container_name: postgresdb
    image: postgres
    environment:
      POSTGRES_USER: shuaibu
      POSTGRES_PASSWORD: products
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    restart: unless-stopped

volumes:
  postgres:
